project/models.py
from project import db
from project import bcrypt
from sqlalchemy.orm import relationship
from sqlalchemy import ForeignKey
import datetime


categories_posts = db.Table(
    'categories_posts',
    db.Column('category_id', db.Integer, db.ForeignKey('categories.id')),
    db.Column('post_id', db.Integer, db.ForeignKey('posts.id')),
    db.PrimaryKeyConstraint('post_id', 'category_id')
)

class CategoriesPosts(object):

    def __init__(self, category_id, post_id):
        self.post_id = post_id
        self.category_id = category_id


db.mapper(CategoriesPosts, categories_posts)

class BlogPost(db.Model):

    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), nullable=False)
    description = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default= datetime.datetime.utcnow())
    author_id = db.Column(db.Integer, ForeignKey("users.id"))
    comments = relationship("Comment", backref="comments")
    categories = db.relationship('Category', secondary=categories_posts,
                                       backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, title, description, author):
        self.title = title
        self.description = description
        self.author_id = author

    def __repr__(self):
        return 'title {}| {}'.format(self.title, self.description)


class Category(db.Model):

    __tablename__ = 'categories'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return self.name


class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    post_id = db.Column(db.Integer, ForeignKey('posts.id'))
    user_id = db.Column(db.Integer, ForeignKey('users.id'), default=1)
    title = db.Column(db.String(80), nullable=False)
    content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow())

    def __init__(self, post_id, user_id, title, content):
        self.post_id = post_id
        self.user_id = user_id
        self.title = title
        self.content = content

    def __repr__(self):
        return 'zadeva: {} | {}'.format(self.title, self.content)


class User(db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(155), nullable=False)
    email = db.Column(db.String(80), nullable=False)
    password = db.Column(db.String(60), nullable=False)
    posts = relationship("BlogPost", backref="author")
    comments = relationship("Comment", backref="commentator")

    def __init__(self, name, email, password):
        self.name = name
        self.email = email
        self.password = bcrypt.generate_password_hash(password)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)

    def __repr__(self):
        return '<name {}'.format(self.name)

project/blog/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField,SelectMultipleField
from wtforms.validators import DataRequired


class CreatePostForm(Form):
    title = StringField('title', validators=[DataRequired(message='Vnos tega polja je obvezen')])
    description = TextAreaField('description', validators=[DataRequired(message='Vnos tega polja je obvezen')])
    categories = SelectMultipleField('categories')

class CommentForm(Form):
    title = StringField('title', validators=[DataRequired(message='Vnos tega polja je obvezen')])
    content = TextAreaField('content', validators=[DataRequired(message='Vnos tega polja je obvezen')])

project/users/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class LoginForm(Form):
    username = StringField('Username', validators=[DataRequired( message='Vnos tega polja je obvezen')])
    password = PasswordField('Password', validators=[DataRequired(message='Vnos tega polja je obvezen')])


class RegisterForm(Form):
    username = StringField('username', validators=[DataRequired(message='Vnos tega polja je obvezen'), Length(min=3, max=25)])
    email = StringField('email', validators=[DataRequired(message='Vnos tega polja je obvezen'), Length(min=6, max=40), Email(message=None)])
    password = PasswordField('password', validators=[DataRequired(message='Vnos tega polja je obvezen'), Length(min=6, max=25)])
    confirm = PasswordField('Repeat password', validators=[DataRequired(message='Vnos tega polja je obvezen'), EqualTo('password', message="Gesli se morata obvzno ujemati")])

project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask.ext.bcrypt import Bcrypt
from flask.ext.login import LoginManager, current_user

app = Flask(__name__)
# bcrypt enabled
bcrypt = Bcrypt(app)
# flask login enabled
login_manager = LoginManager()
login_manager.init_app(app)


#config
app.config.from_object('config.DevConfig')

# SQLAlchemy object - povezava z bazo
db = SQLAlchemy(app)

from models import *
from project.users.views import users_blueprint
from project.home.views import home_blueprint
from project.blog.views import blog_blueprint

app.register_blueprint(users_blueprint)
app.register_blueprint(home_blueprint)
app.register_blueprint(blog_blueprint)

# katera funkcija se ukvarja z logiranjem uporabnikov flask-login
from models import User
login_manager.login_view = 'users.login'
login_manager.login_message = 'Za ogled te strani je obvezna prijava.'

# pridobi uporabnika iz baze in shrani v cookie flask -login obvezno
@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()

project/blog/views.py
# -*- coding: utf-8 -*-
from flask import request, render_template, redirect, url_for, flash, Blueprint
from project import db
from flask_login import login_required, current_user
from project.models import BlogPost, Comment, CategoriesPosts, Category
from forms import CreatePostForm, CommentForm
from project.helpers import date_time_standard

blog_blueprint = Blueprint(
    'blog', __name__,
    template_folder='templates'
)


@blog_blueprint.route('/blog')
@login_required
def blog_home():
    posts = db.session.query(BlogPost).order_by('id desc').all()
    return render_template('blog_home.html', posts=posts)



@blog_blueprint.route('/blog-post/<post_id>')
@login_required
def blog_details(post_id):
    form = CommentForm()
    post = BlogPost.query.filter_by(id=post_id).first()
    objavljeno = date_time_standard(post.created_at)
    comments = db.session.query(Comment).filter_by(post_id=post_id).all()
    return render_template('post_details.html', post=post, form=form, comments=comments, objavljeno=objavljeno)


@blog_blueprint.route('/blog-post/<post_id>/create-comment', methods=['POST'])
@login_required
def create_commment(post_id):
    post = BlogPost.query.filter_by(id=post_id).first()
    form = CommentForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data

        comment = Comment(
            post_id=post_id,
            user_id=current_user.id,
            title=title,
            content=content
        )
        db.session.add(comment)
        db.session.commit()
        flash('Komentar shranjen OK')
        return redirect(url_for('blog.blog_details',post_id=post_id))


@blog_blueprint.route('/blog/create-post', methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        categories = request.form.getlist('categories')

        post = BlogPost(
            title=title,
            description=description,
            author=current_user.id
        )
        list_categories = []
        for c in categories:
            c = int(c)
            list_categories.append(c)

        db.session.add(post)
        db.session.commit()

        for category in list_categories:
            c = CategoriesPosts(
                category_id=category,
                post_id= post.id
            )
            db.session.add(c)
            db.session.commit()

        flash('Objava je bila shranjena')
        return redirect(url_for('blog.blog_home'))

    categories = db.session.query(Category).all()
    return render_template('create_post.html',categories=categories)


@blog_blueprint.route('/blog/dashboard', methods=['GET', 'POST'])
def dashboard():
    posts = db.session.query(BlogPost).order_by('created_at desc').all()

    for post in posts:
        post.created_at = date_time_standard(post.created_at)

    categories = db.session.query(Category).all()

    if request.method == 'POST':
        name = request.form['name']
        category = Category(name=name)

        db. session.add(category)
        db.session.commit()
        flash('Kategorija dodana OK')

        return redirect(url_for('blog.dashboard'))

    return render_template('blog_dashboard.html', posts=posts, categories=categories)

project/home/views.py
from flask import render_template, request, redirect, url_for, session, flash, Blueprint
from project import db
from project.models import BlogPost
from urllib import urlopen
import json



# blueprint config
home_blueprint = Blueprint(
    'home', __name__,
    template_folder='templates'
)


# routing
@home_blueprint.route('/')
def home():
    url = 'http://api.openweathermap.org/data/2.5/weather?q=Cerkno,uk&units=metric&appid=425d08d39ad4a87c17bcb351795ba4c3'
    result = urlopen(url).read()
    weather = json.loads(result)
    posts = db.session.query(BlogPost).order_by('id desc').limit(3).all()
    return render_template('index.html', posts=posts, weather=weather)


@home_blueprint.route('/welcome')
def welcome():
    return render_template('welcome.html')

@home_blueprint.route('/contact')
def contact():
	return render_template('contact.html')

project/users/views.py
from flask import flash, redirect, url_for, render_template, request, session, Blueprint
from flask.ext.login import login_user, login_required, logout_user, current_user
from forms import LoginForm, RegisterForm
from project.models import User, bcrypt
from project import db

# config blueprint struktura projekta
users_blueprint = Blueprint(
    'users', __name__,
    template_folder='templates'
)


# routes
@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(name=request.form['username']).first()
            if user is not None and bcrypt.check_password_hash(user.password, request.form['password']):
                login_user(user)
                flash("Prijava uspela pijavljen is kot {}".format(current_user.name))
                return redirect(url_for('blog.blog_home'))
            error = 'Napaka: Nepravilen uporabnik oziroma geslo. Prosim poskusi znova'
        else:
            return render_template('login.html', form=form, error=error)

    return render_template('login.html', form=form, error=error)


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            # shrani podatke v bazo
            user = User(
                name=form.username.data,
                email=form.email.data,
                password=form.password.data
            )
            db.session.add(user)
            db. session.commit()

            # avtomatsko prijavi uporabnika
            login_user(user)
            flash('Registracija uporabnika je uspela. Prijavljen si kot {} '.format(current_user.name))
            return redirect(url_for('blog.blog_home'))

    return render_template('register.html', form=form)


# odjavi uporabnika session.pop vzame logged_in True in zamenja z None
# izbris secret key - cookie
@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Odjava je uspela! ")
    return redirect(url_for('home.welcome'))

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap linki -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

	<!-- jquery cdn -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/redmond/.jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <!-- moj css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='theme.css')}}">
    <title>{% block title%}{% endblock title %}</title>
</head>
<body>
<div class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav_zg">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">Falsk App</a>
        </div>
        <div class="collapse navbar-collapse" id="nav_zg">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Domov</a></li>
                <li><a href="{{ url_for('home.welcome') }}">O Aplikaciji</a></li>
                <li><a href="{{ url_for('home.contact') }}">Kontakt</a></li>
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('blog.blog_home')}}">Blog</a></li>
                    <li class="dropdown">
                        <a href="#"class="dropdown-toggle" data-toggle="dropdown">
                        {{ current_user.name }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('blog.dashboard')}}">Dashboard</a></li>
                            <li><a href="{{ url_for('users.logout') }}">Odjava</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="dropdown">
                        <a href="#"class="dropdown-toggle" data-toggle="dropdown">
                        Gost
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('users.register')}}">Registracija</a></li>
                            <li><a href="{{ url_for('users.login') }}">Prijava</a></li>
                        </ul>
                    </li>
                {% endif %}

            </ul>
        </div>
        </div>
    </div>
</div>
<!-- konec navigacije zgoraj -->
<div class="container">
    <!-- child template content -->
    {%block heading %}
    <!-- glavni naslov -->
    {% endblock heading%}

    <!-- vsebina -->
    {% block content %}

    {% endblock content %}
</div>

</body>
</html>