project/blog/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField,SelectMultipleField
from wtforms.validators import DataRequired


class CreatePostForm(Form):
    title = StringField('title', validators=[DataRequired(message='Vnos tega polja je obvezen')])
    description = TextAreaField('description', validators=[DataRequired(message='Vnos tega polja je obvezen')])
    categories = SelectMultipleField('categories')

class CommentForm(Form):
    title = StringField('title', validators=[DataRequired(message='Vnos tega polja je obvezen')])
    content = TextAreaField('content', validators=[DataRequired(message='Vnos tega polja je obvezen')])

project/blog/views.py
# -*- coding: utf-8 -*-
from flask import request, render_template, redirect, url_for, flash, Blueprint
from project import db
from flask_login import login_required, current_user
from project.models import BlogPost, Comment, CategoriesPosts, Category
from forms import CreatePostForm, CommentForm
from project.helpers import date_time_standard

blog_blueprint = Blueprint(
    'blog', __name__,
    template_folder='templates'
)


@blog_blueprint.route('/blog')
@login_required
def blog_home():
    posts = db.session.query(BlogPost).order_by('id desc').all()
    return render_template('blog_home.html', posts=posts)



@blog_blueprint.route('/blog-post/<post_id>')
@login_required
def blog_details(post_id):
    form = CommentForm()
    post = BlogPost.query.filter_by(id=post_id).first()
    objavljeno = date_time_standard(post.created_at)
    comments = db.session.query(Comment).filter_by(post_id=post_id).all()
    return render_template('post_details.html', post=post, form=form, comments=comments, objavljeno=objavljeno)


@blog_blueprint.route('/blog-post/<post_id>/create-comment', methods=['POST'])
@login_required
def create_commment(post_id):
    post = BlogPost.query.filter_by(id=post_id).first()
    form = CommentForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data

        comment = Comment(
            post_id=post_id,
            user_id=current_user.id,
            title=title,
            content=content
        )
        db.session.add(comment)
        db.session.commit()
        flash('Komentar shranjen OK')
        return redirect(url_for('blog.blog_details',post_id=post_id))


@blog_blueprint.route('/blog/create-post', methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        categories = request.form.getlist('categories')

        post = BlogPost(
            title=title,
            description=description,
            author=current_user.id
        )
        list_categories = []
        for c in categories:
            c = int(c)
            list_categories.append(c)

        db.session.add(post)
        db.session.commit()

        for category in list_categories:
            c = CategoriesPosts(
                category_id=category,
                post_id= post.id
            )
            db.session.add(c)
            db.session.commit()

        flash('Objava je bila shranjena')
        return redirect(url_for('blog.blog_home'))

    categories = db.session.query(Category).all()
    return render_template('create_post.html',categories=categories)


@blog_blueprint.route('/blog/dashboard', methods=['GET', 'POST'])
def dashboard():
    posts = db.session.query(BlogPost).order_by('created_at desc').all()

    for post in posts:
        post.created_at = date_time_standard(post.created_at)

    categories = db.session.query(Category).all()

    if request.method == 'POST':
        name = request.form['name']
        category = Category(name=name)

        db. session.add(category)
        db.session.commit()
        flash('Kategorija dodana OK')

        return redirect(url_for('blog.dashboard'))

    return render_template('blog_dashboard.html', posts=posts, categories=categories)

project/home/views.py
from flask import render_template, request, redirect, url_for, session, flash, Blueprint
from project import db
from project.models import BlogPost
from urllib import urlopen
import json



# blueprint config
home_blueprint = Blueprint(
    'home', __name__,
    template_folder='templates'
)


# routing
@home_blueprint.route('/')
def home():
    url = 'http://api.openweathermap.org/data/2.5/weather?q=Cerkno,uk&units=metric&appid=425d08d39ad4a87c17bcb351795ba4c3'
    result = urlopen(url).read()
    weather = json.loads(result)
    posts = db.session.query(BlogPost).order_by('id desc').limit(3).all()
    return render_template('index.html', posts=posts, weather=weather)


@home_blueprint.route('/welcome')
def welcome():
    return render_template('welcome.html')

@home_blueprint.route('/contact')
def contact():
	return render_template('contact.html')

project/blog/templates/blog_dashboard.html
{% extends "base.html" %}

{% block title %} Blog {% endblock title %}

{% block content %}
<div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="page-header">
                <h1>Blog Nadzorna plošča </h1>
                <p>
                   Pregled vsega dogajanja na blogu
                </p>
            </div>
        </div>
    </div>
<!-- flashed messages section  -->
    <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                {% for message in get_flashed_messages() %}
                    <div class="alert alert-success">
                        <span class="glyphicon glyphicon-ok"></span>
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
    </div>
<!-- blog nav section button group -->
<div class="row">
    <div class="col-sm-8">
        <div class="btn-group" role="group">
          <a href="{{ url_for('blog.create_post')}}" role="button" class="btn btn-primary btn-lg">
              <span class="glyphicon glyphicon-pencil"></span>
              Nova objava
          </a>
          <a href="{{ url_for('home.home')}}" role="button" class="btn btn-primary btn-lg">
              <span class="glyphicon glyphicon-home"></span>
              Domov
          </a>
          <a href="{{url_for('blog.blog_home')}}" type="button" class="btn btn-primary btn-lg">
              <span class="glyphicon glyphicon-asterisk"></span>
             Blog
          </a>
        </div>
    </div>
</div>
<hr>
<!-- blog posts - main content -->

<div class="row">
    {% if posts|length > 0 %}
        <div class="col-sm-8">
            <table class="table table-responsive table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Naslov</th>
                        <th>avtor</th>
                        <th>Objavljeno</th>
                    </tr>
                </thead>
                <tbody class="bg-info">
                    {% for post in posts %}
                        <tr>
                            <td><a href="/blog-post/{{ post.id}}"> {{ post.title }}</a></td>
                            <td>{{ post.author.name }}</td>
                            <td>{{ post.created_at }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col-sm-4">
            <div class="page-header">
                <h2>Hitri pregled </h2>
                <p>
                    <span class="krepko">Število objav:</span> <span class="badge">{{ posts|length }}</span>
                </p>
            </div>
        </div>
    {% else %}
        <div class="col-sm-6 col-sm-offset-3">
           <div class="alert alert-info">
               <span class="glyphicon glyphicon-info-sign"></span>
               Trenutno v bazi ni nobene objave za dodajanje nove klikni na Napiši objavo
           </div>
        </div>
    {% endif %}
    <div class="col-sm-4">
        <h3>Kategorije</h3>
        <br>
        <form action="" method="post" class="form-inline">
            <div class="form-group">
                <input type="text" name="name" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span> Dodaj
            </button>
        </form>
        <hr>
        <ul class="list-group">
            {% for category in categories %}
                <li class="list-group-item"> {{ category.name }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

project/blog/templates/blog_home.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}

{% block content %}
<div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="page-header">
                <h1>Blog </h1>
                <p>
                    Moje najrazličnejše pisarije bodo vidne tukaj spodaj :)
                </p>
            </div>
        </div>
    </div>
<!-- flashed messages section  -->
    <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                {% for message in get_flashed_messages() %}
                    <div class="alert alert-success">
                        <span class="glyphicon glyphicon-ok"></span>
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
    </div>
<!-- blog nav section button group -->
<div class="row">
    <div class="col-sm-8">
        <div class="btn-group" role="group">
          <a href="{{ url_for('blog.create_post')}}" role="button" class="btn btn-primary btn-lg">
              <span class="glyphicon glyphicon-pencil"></span>
              Nova objava
          </a>
          <a href="{{ url_for('home.home')}}" role="button" class="btn btn-primary btn-lg">
              <span class="glyphicon glyphicon-home"></span>
              Domov
          </a>
          <a href="{{url_for('home.welcome')}}" type="button" class="btn btn-primary btn-lg">
              <span class="glyphicon glyphicon-asterisk"></span>
              O Aplikaciji
          </a>
        </div>
    </div>
</div>
<hr>
<!-- blog posts - main content -->

<div class="row">
    {% if posts|length > 0 %}
        <div class="col-sm-8">
            <div class="panel panel-primary">
                <div class="panel-body">
                    {% for post in posts %}
                        <h2>{{ post.title }}</h2>
                        <span class="text-muted">avtor: {{ post.author.name }}</span>
                        <p>
                            {{post.description }}
                        </p>
                        <p>
                            <a href="/blog-post/{{ post.id}}" class="btn btn-primary">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                                Več
                            </a>
                        </p>
                        <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="page-header">
                <h2>Hitri pregled </h2>
                <p>
                    <span class="krepko">Število objav:</span> <span class="badge">{{ posts|length }}</span>
                </p>
            </div>
        </div>
    {% else %}
        <div class="col-sm-6 col-sm-offset-3">
           <div class="alert alert-info">
               <span class="glyphicon glyphicon-info-sign"></span>
               Trenutno v bazi ni nobene objave za dodajanje nove klikni na Napiši objavo
           </div>
        </div>
    {% endif %}
</div>
{% endblock content %}

project/blog/templates/create_post.html
{% extends "base.html" %}

{% block title %} Nova objava {% endblock title %}

{% block heading %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="page-header">
            <h1>Napiši novo objavo</h1>
        </div>
    </div>
</div>
{% endblock heading %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <form action="" method="post" class="form-horizontal">
            <div class="from-group">
                <label for="title" class="control-label col-sm-4">Naslov</label>
                <div class="col-sm-8">
                    <input type="text" id="title" name="title" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label for="description" class="control-label col-sm-4">Vsebina</label>
                <div class="col-sm-8">
                    <textarea name="description" id="description" cols="30" rows="10" class="form-control">

                    </textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="categories" class="control-label col-sm-4">Kategorije</label>
                {% for category in categories %}
                    <div class="col-sm-8 col-sm-offset-4">
                        <input type="checkbox" name="categories" value="{{ category.id }}" class="checkbox-inline" id="categories">
                        {{ category.name }}
                    </div>
                {% endfor %}
            </div>
            <hr>
            <div class="form-group">
                <div class="col-sm-8 col-sm-offset-4">
                    <button type="submit" class="btn btn-block btn-success">
                    <span class="glyphicon glyphicon-save"></span>
                    Shrani Objavo
                </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

project/blog/templates/post_details.html
{% extends "base.html" %}

{% block title %}
    Podrobnosti objave
{% endblock title %}

{% block heading %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="page-header">
            <h1>{{ post.title }}</h1>
        </div>
    </div>
</div>
{%  endblock heading %}

{% block content %}
{% for message in get_flashed_messages() %}
     <div class="row">
         <div class="col-sm-6 col-sm-offset-3">
             <div class="alert alert-success">
                 <span class="glyphicon glyphicon-ok"></span> 
                 {{ message }}
             </div>
         </div>
     </div>
{% endfor %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="panel panel-primary">
            <div class="panel-body">
                <p>
                    <span class="krepko">Objavljeno:</span> {{ objavljeno }}
                </p>
                <p>
                    <span class="krepko">Avtor:</span> {{ post.author.name }}
                </p>
                <p>
                    <span class="krepko">Kategorije</span>:
                    {% for post_category in post.categories %}
                        <span class="text-muted">{{ post_category.name }}</span>
                    {% endfor %}
                </p>
                <p>
                    <span class="krepko">Vsebina: </span> {{ post.description }}
                </p>
                <hr />
                <a href="{{ url_for('blog.blog_home') }}" class="btn btn-danger">Nazaj</a>
            </div>
        </div>
        <h2>Komentarji</h2>
        {% if comments|length == 0 %}
            <div class="alert alert-info">
                <span class="glyphicon glyphicon-info-sign"></span>
                Za to objavo ni komentarjev Bodi porvi in napiši komentar
            </div>
        {% else %}
            {% for comment in comments %}
                <div class="well">
                    <h3>{{ comment.title }}</h3>
                    <p>
                        <span class="text-muted">avtor: </span> {{ comment.commentator.name}}
                        <span class="text-muted">datum: </span> {{ comment.created_at }}

                    </p>
                    <p>
                        {{ comment.content}}
                    </p>
                </div>
            {% endfor %}
        {% endif %}
        <hr>
    <h3>Tvoj komentar </h3>
    <form action="{{ url_for('blog.create_commment', post_id=post.id)}}" method="post">
            {{ form.csrf_token}}
            <div class="form-group">
                <label>Zadeva</label>
                {{ form.title(class="form-control") }}
                {% if form.title.errors %}
                    {% for error in form.title.errors %}
                        <span class="krepko text-danger"> {{ error}}</span>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                <label>Komentar </label>
                {{ form.content(class="form-control")}}
                {% if form.content.errors %}
                    {% for error in form.content.errors %}
                        <span class="krepko text-danger"> {{ error}}</span>
                    {% endfor %}
                {% endif %}
            </div>
            <br>
            <div class="form-group">

                <button type="submit" class="btn  btn-success">
                    Shrani Objavo
                </button>

            </div>
        </form>
    </div>
</div>


{% endblock content %}